apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Values.image.imagePullSecret }}-{{ .Values.stage }}"
  namespace: {{ .Chart.Name }}-{{ .Values.stage }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.image.dockerconfigjson }}
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Values.image.imagePullSecret }}-{{ .Values.stage }}"
      namespace: {{ .Chart.Name }}-{{ .Values.stage }}
    type: kubernetes.io/dockerconfigjson

