apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: "{{ .Chart.Name }}-{{ .Values.stage }}-secret"
  namespace: "{{ .Chart.Name }}-{{ .Values.stage }}"
spec:
  encryptedData:
    CORS_ORIGINS: "{{ .Values.encryptedData.corsOrigins }}"
    DB_HOST: "{{ .Values.encryptedData.dbHost }}"
    DB_NAME: "{{ .Values.encryptedData.dbName }}"
    DB_PASSWORD: "{{ .Values.encryptedData.dbPassword }}"
    DB_PORT: "{{ .Values.encryptedData.dbPort }}"
    DB_PROTOCOL: "{{ .Values.encryptedData.dbProtocol }}"
    DB_USER: "{{ .Values.encryptedData.dbUser }}"
    PM_MAIL_ADDRESSES: "{{ .Values.encryptedData.pmMailAddresses }}"
    SMTP_HOST: "{{ .Values.encryptedData.smtpHost }}"
    SMTP_PASSWORD: "{{ .Values.encryptedData.smtpPassword }}"
    SMTP_SENDER: "{{ .Values.encryptedData.smtpSender }}"
    SMTP_USERNAME: "{{ .Values.encryptedData.smtpUsername }}"
    STAGE: "{{ .Values.encryptedData.stage }}"
  template:
    metadata:
      creationTimestamp: null
      name: "{{ .Chart.Name }}-{{ .Values.stage }}-secret"
      namespace: "{{ .Chart.Name }}-{{ .Values.stage }}"

