apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.stage }}"
  namespace: "{{ .Chart.Name }}-{{ .Values.stage }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Chart.Name }}-{{ .Values.stage }}"
  ports:
    - port: {{ .Values.image.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.image.containerPort }}

